sudo: false
dist: trusty

language: node_js

node_js:
  - "8.0.0"
  - "8"
  - "9"
  - "10"
  - "11"
  - "12"
  - "13"
  - "node"

before_script: npm run test-prepare
script: npm test

branches:
  except:
    - gh-pages

jobs:
  include:
    - stage: npm lint
      node_js: "node"
      script: npm run lint

notifications:
  email:
    on_success: never
    on_failure: always
